import type { ReactNode } from "react";
import { requireAuth } from "@/server/lib/auth-guard";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stripe Protected Route",
  description: "Generated by create next app",
};

const ProtectedLayout = async ({ children }: { children: ReactNode }) => {
  await requireAuth();
  return <>{children}</>;
};

export default ProtectedLayout;
